/**
 * Writes the list of URLs the service worker precaches at install.
 *
 * This has to be generated, and it has to be generated from the *built*
 * manifest. A service worker only starts controlling a page after it activates,
 * which is after that first page has already fetched its assets, so on a first
 * visit every /static/* request goes around the worker and its fetch handler
 * caches nothing. Runtime caching alone therefore leaves a first-time visitor
 * with a cached document and no code to run it — an offline start that finds
 * the shell and then dies. Only an install-time precache closes that window.
 *
 * Run after `vite build --mode client`, which is what produces the manifest
 * these names come from; see the `build` script.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const MANIFEST = join(ROOT, 'dist/.vite/manifest.json')
const OUT = join(ROOT, 'app/sw/precache.ts')

type Chunk = { file?: string; css?: string[] }

const manifest: Record<string, Chunk> = JSON.parse(readFileSync(MANIFEST, 'utf8'))

const hashed = new Set<string>()
for (const chunk of Object.values(manifest)) {
  if (chunk.file) hashed.add(`/${chunk.file}`)
  for (const css of chunk.css ?? []) hashed.add(`/${css}`)
}

/*
 * Weather icons are listed rather than globbed at runtime: the timeline renders
 * one per waypoint, and a row whose icon 404s offline is a row that looks like
 * missing data. They are ~440 kB of SVG in total, which is the price of a
 * timeline that reads the same with no signal.
 */
const icons = readdirSync(join(ROOT, 'public/wx'))
  .filter((f) => f.endsWith('.svg'))
  .map((f) => `/wx/${f}`)

const fonts = readdirSync(join(ROOT, 'public/fonts'))
  .filter((f) => f.endsWith('.woff2'))
  .map((f) => `/fonts/${f}`)

/*
 * Every language's document, because each is a separate server-rendered URL and
 * the offline start has to work in the language the reader actually uses.
 */
const shells = ['/', '/de', '/fr']

const urls = [
  ...shells,
  '/manifest.webmanifest',
  '/icon.svg',
  // Shown on the lock screen by a background push, which is exactly when the
  // network may be gone.
  '/icon-192.png',
  ...[...hashed].sort(),
  ...fonts.sort(),
  ...icons.sort()
]

const body = `// Generated by scripts/precache-manifest.ts. Do not edit.
export const PRECACHE: readonly string[] = ${JSON.stringify(urls, null, 2)}
`

writeFileSync(OUT, body)
console.log(`precache: ${urls.length} urls -> app/sw/precache.ts`)
